service: aws-lambda-twilio-2

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  environment:
    # replace these env variables with your twilio account values
    TWILIO_ACCOUNT_SID: AC0222927841644a5655ef25a444af6f28
    TWILIO_AUTH_TOKEN: 4dffbde8e9dccf0d6fd796778e9ee569
    TWILIO_PHONE_NUMBER: +46769439728

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: api/sendText
          method: post