service: aws-lambda-twilio-2

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  environment:

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: api/sendText
          method: post